# Basic pipeline. Will run unit tests, build and push a new docker image, then deploy on heroku

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: Executing Unit Tests
    jobs:
      - job: UnitTest
        steps:
          - bash: echo Should run unit tests here
  - stage: Compile
    dependsOn: Test
    displayName: Compiling TS into JS
    jobs:
      - job: Compilation
        steps:
          - script: |
              npm install
              npm run build
  - stage: Dockerize
    dependsOn: Compile
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub connection'
            repository: 'achung98/covid-tracker'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'
  - stage: Deploy
    dependsOn: Dockerize
    jobs:
      - job: HerokuDockerRegistry
        displayName: Push Image to Heroku Docker Registry
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - script: |
              sudo docker login --username=achung998 --password=$(herokupass) registry.heroku.com
              sudo docker build -t registry.heroku.com/$(app)/web .
              sudo docker push registry.heroku.com/$(app)/web
              sudo docker login --username=achung998 --password=$(herokupass) registry.heroku.com
              sudo heroku container:release web -a $(app)